package org.example;

public enum Options {
    PRINT_MENU, FIND_AND_DISPLAY_ALL_EMPLOYEES, FIND_EMPLOYEE_BY_ID, FIND_AND_DISPLAY_ALL_EMPLOYEES_JSON, FIND_EMPLOYEE_BY_ID_JSON, DELETE_EMPLOYEE_BY_ID, ADD_EMPLOYEE, QUIT
}
